### ISSUE TITLE
Scope Capture Receipt as an API product

### ISSUE THREAD

**Issue by ricardobrg** [tiki/capture#3]
### Reason
The Capture Receipt is currently used as a library that enables the App Receipt to capture data from scanning physical receipts, scraping email accounts and connecting online retailer accounts.

Now we want to transform this library in a standalone product that makes it possible not only the capturing of the data but its licensing and publishing. It will simplify our internal usage, moving the business logic out of the apps layer, and will allow other organizations to use with their users.

### Description
Create the documentation and the API definitions for Capture Receipt. 

Features:
- Get data from physical and digital receipts with Microblink
- Handle data licensing and payables with TIKI
- Publish data to TIKI

### Success criteria
- [x] API documentation
- [x] Stories to implement

**Comment by ricardobrg** [comment]
Android initial docs and setup
https://github.com/tiki/capture-receipt-ios/tree/6f2846652a134a9df0ecffec28ae95f63808e447

iOS initial docs and setup
https://github.com/tiki/capture-receipt-ios/tree/6f2846652a134a9df0ecffec28ae95f63808e447

**Comment by mike-audi** [comment]
**Config**
- This should just take in a string for the legal terms. There is no UI (other than the scan camera) so the agreement templating needs to happen before calling the capture sdk. 

- Don't we need to add an optional google id for supporting oauth?


**Receipts**
- We should rename the `receipts` endpoint to scrape for naming consistency with `scan` since scan also returns receipts.

**Comment by ricardobrg** [comment]
> **Config**
> 
> * This should just take in a string for the legal terms. There is no UI (other than the scan camera) so the agreement templating needs to happen before calling the capture sdk.

👍 

> * Don't we need to add an optional google id for supporting oauth?

There is optional config for that
Android: https://github.com/tiki/capture-receipt-android/blob/main/README.md#initialize-gmail-andor-outlook-apis: 
iOS: https://github.com/tiki/capture-receipt-ios/tree/6f2846652a134a9df0ecffec28ae95f63808e447

> **Receipts**
> 
> * We should rename the `receipts` endpoint to scrape for naming consistency with `scan` since scan also returns receipts.

Yes, I am stuck on ideas with that... Microblink uses digital/ereceipt. I thing that digital is good, but I am not very excited with it...

**Comment by mike-audi** [comment]
> > **Config**
> > 
> > * This should just take in a string for the legal terms. There is no UI (other than the scan camera) so the agreement templating needs to happen before calling the capture sdk.
> 
> 👍
> 
> > * Don't we need to add an optional google id for supporting oauth?
> 
> There is optional config for that Android: https://github.com/tiki/capture-receipt-android/blob/main/README.md#initialize-gmail-andor-outlook-apis: iOS: https://github.com/tiki/capture-receipt-ios/tree/6f2846652a134a9df0ecffec28ae95f63808e447
> 
> > **Receipts**
> > 
> > * We should rename the `receipts` endpoint to scrape for naming consistency with `scan` since scan also returns receipts.
> 
> Yes, I am stuck on ideas with that... Microblink uses digital/ereceipt. I thing that digital is good, but I am not very excited with it...

Just use either `read` or `scrape` since that's what it actually is.

**Comment by ricardobrg** [comment]
Android specs

tiki/capture-receipt-android/issues/1
tiki/capture-receipt-android/issues/2
tiki/capture-receipt-android/issues/3
tiki/capture-receipt-android/issues/4
tiki/capture-receipt-android/issues/5
tiki/capture-receipt-android/issues/6
tiki/capture-receipt-android/issues/7
tiki/capture-receipt-android/issues/8
